version: '3.8'

services:
  bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=string
      - CHAT_ID=string
      - POSTMAN_API_KEY=string
      - COLLECTION_ID=string
      - USER_SEND_IDS=string
    ports:
      - "3000:3000"
